# Generated by Django 4.1 on 2022-08-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0002_rename_unit_number_unit_course_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='first_day',
            field=models.CharField(choices=[('0', 'Saturday'), ('1', 'Sunday'), ('2', 'Monday'), ('3', 'Tuesday'), ('4', 'Wednesday')], default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='unit',
            name='second_day',
            field=models.CharField(choices=[('0', 'Saturday'), ('1', 'Sunday'), ('2', 'Monday'), ('3', 'Tuesday'), ('4', 'Wednesday')], default='0', max_length=10),
        ),
    ]
